service: daily-market-update
org: dappner
app: daily-market-update
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  profile: my-dashboard
  environment:
    SUPABASE_URL: ${ssm:/daily-market-update/supabase-url}
    SUPABASE_KEY: ${ssm:/daily-market-update/supabase-key}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ssm:GetParameter
          Resource: "arn:aws:ssm:${aws:region}:${aws:accountId}:parameter/daily-market-update/*"

plugins:
  - serverless-python-requirements

package:
  individually: true
  patterns:
    - "!node_modules/**"
    - "!tests/**"
    - "!__pycache__/**"
    - "!.pytest_cache/**"
    - "!.git/**"
    - "!.github/**"
    - "!.vscode/**"
    - "!*.dist-info/**"
    - "!*.egg-info/**"

functions:
  processTickerData:
    handler: src.lambda_handler.lambda_handler
    events:
      # 6:00 AM Eastern Time
      - schedule:
          # 6:00 AM EDT = 10:00 UTC (March to November)
          rate: cron(0 10 ? * MON-SUN *)
          enabled: true
      - schedule:
          # 6:00 AM EST = 11:00 UTC (November to March)
          rate: cron(0 11 ? * MON-SUN *)
          enabled: true
      # 12:00 PM Eastern Time (Noon)
      - schedule:
          # 12:00 PM EDT = 16:00 UTC (March to November)
          rate: cron(0 16 ? * MON-SUN *)
          enabled: true
      - schedule:
          # 12:00 PM EST = 17:00 UTC (November to March)
          rate: cron(0 17 ? * MON-SUN *)
          enabled: true
      # 5:30 PM Eastern Time (after NYSE close)
      - schedule:
          # 5:30 PM EDT = 21:30 UTC (March to November)
          rate: cron(30 21 ? * MON-FRI *)
          enabled: true
      - schedule:
          # 5:30 PM EST = 22:30 UTC (November to March)
          rate: cron(30 22 ? * MON-FRI *)
          enabled: true
      # 12:00 AM Eastern Time (Midnight)
      - schedule:
          # 12:00 AM EDT = 04:00 UTC (March to November)
          rate: cron(0 4 ? * MON-SUN *)
          enabled: true
      - schedule:
          # 12:00 AM EST = 05:00 UTC (November to March)
          rate: cron(0 5 ? * MON-SUN *)
          enabled: true
    timeout: 300 # 5 minutes
    memorySize: 512
